language: node_js
node_js:
  - "0.10"

branches:
  only:
    - master
    - avocet/test-tests

env:
  global:
    - OAE_TEST_INTEGRATION=false
    - secure: ByuH243AwF67+aPXbLLwMOgZKlETnC0AcspFO3iIV9vbcpUyTUGjR1l9/HbOof6NwpdgXYw93nkSyKvqj7yKXVJmGq77j1+lKKPra1/IidiFvb9ELel241g2TLwk7FQ47NbkCMtcn4g8z4RrTl4yMtZKx17qfCNK/iMERiGHSJ4=
    - secure: e47epKU9R/F6fHoAFOTUp0CK7+/W+od0C9cp5sul5ovxGlbb2ep9UmdyLIwUL+FiAAZS813szCOusgrVLS2jyZeu3+pz6/jhIANbUjdIgpSoqkTRlUcnlYh3l6IsvlcUfU6MjQ1EsQd1waw//M4KKZQgsnc+dMV89cn5m0Hks50=

before_install:
  # Add DataStax apt repo for Cassandra
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/dsc.sources.list

  # Add PPA repos for miscellaneous dependencies
  - echo 'yes' | sudo add-apt-repository ppa:oae/deps
  - echo 'yes' | sudo add-apt-repository ppa:coolwanglu/pdf2htmlex
  - sudo apt-get update

  # Install cassandra 1.2 manually
  #- sudo apt-get install -y -o Dpkg::Options::=--force-confnew cassandra=1.2.16
  #- sudo sed -i 's/-Xss180k/-Xss256k/g' /etc/cassandra/cassandra-env.sh
  #- sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  #- sudo service cassandra stop
  #- sudo service cassandra start
  #- sudo service cassandra status
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/1.2.19/apache-cassandra-1.2.19-bin.tar.gz
  - echo "06e0a3d4242405bbf1b6094e409d6e18  apache-cassandra-1.2.19-bin.tar.gz" | md5sum --check -
  - tar -xvzf apache-cassandra-1.2.19-bin.tar.gz
  - export PATH=`pwd`/apache-cassandra-1.2.19/bin:$PATH
  - which cassandra
  - which cqlsh
  - sudo cassandra


  # Turn off unneeded services to free some memory
  - sudo service mysql stop
  - sudo service memcached stop
  - sudo service postgresql stop

  # We must ensure phantomjs is not available so the travis build will include it in node_modules when deploying
  - sudo rm -rf /usr/local/phantomjs

  # Install Hilary deps
  - sudo apt-get install -qq graphicsmagick libreoffice pdftk chrpath pdf2htmlex
  - npm install -g grunt-cli
  - git clone --depth 1 --branch master git://github.com/CUL-DigitalServices/avocet-ui.git ../avocet-ui

  # Install etherpad
  - cd /usr/src
  - sudo wget https://s3.amazonaws.com/oae-releases/etherpad/1.4/etherpad-1.4.0_node-0.10.17.tar.gz
  - sudo mkdir /opt/etherpad
  - cd /opt/etherpad
  - sudo tar -zxvf /usr/src/etherpad-1.4.0_node-0.10.17.tar.gz > /dev/null
  - sudo touch APIKEY.txt
  - sudo chmod -R 777 .

  # Create a keyspace that we can start etherpad up into. There is a chicken-and-egg problem by having unit tests drop/create and have
  # etherpad be available, so we just create a separate keyspace for it
  - "echo \"CREATE KEYSPACE etherpad WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};\" > /tmp/.create_etherpad_keyspace.cql3"
  - cqlsh -3 -f /tmp/.create_etherpad_keyspace.cql3

  # Configure etherpad
  - "sed -i 's/dbType\" : \"dirty/dbType\" : \"cassandra/g' settings.json"
  - "sed -i 's/\"filename\" : \"var\\/dirty.db\"/\"hosts\": [ \"localhost:9160\" ], \"keyspace\": \"etherpad\", \"cfName\": \"Etherpad\", \"user\": \"\", \"pass\": \"\", \"timeout\": 3000, \"replication\": \"1\", \"strategyClass\": \"SimpleStrategy\", \"cqlVersion\": \"2.0.0\"/g' settings.json"
  - "sed -i 's/defaultPadText\" : \".*\"/defaultPadText\" : \"\"/g' settings.json"
  - echo "13SirapH8t3kxUh5T5aqWXhXahMzoZRA" > APIKEY.txt

  # Start etherpad
  - node node_modules/ep_etherpad-lite/node/server.js &

  # Position ourselves to start the test in "script" phase
  - cd ~/build/CUL-DigitalServices/avocet-hilary

  # Enable preview processing
  - printf "\n\nconfig.previews.enabled = true;" >> config.js
  - printf "\nconfig.previews.office.binary = '/usr/bin/soffice';" >> config.js
  - printf "\nconfig.previews.pdftk.binary = '/usr/bin/pdftk';" >> config.js
  - printf "\nconfig.previews.pdf2htmlEX.binary = '/usr/bin/pdf2htmlEX';" >> config.js

services:
  - elasticsearch
  - rabbitmq
  - redis-server

script:
  - grunt test-coverage-coveralls

after_success:
  # Package and upload to Amazon S3
  - etc/scripts/travis-upload.sh

after_failure:
  - npm install -g bunyan
  - cat tests.log | bunyan -l error

